volumes:
  data:


services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=postgrespw
    ports:
      - 5432:5432
    volumes:
      - data:/var/lib/postgresql
  api:
    build:
      dockerfile: Dockerfile
      context: "./service"
    image: api
  client:
    build:
      dockerfile: Dockerfile
      context: "./react-web-client"
    image: client
    ports:
      - "3000:80"
